# 운영 환경

spring:
  datasource:
    url: ${DB_URL} # 운영용 DB
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate # 테이블 변경 금지
    show-sql: false # SQL 로그 출력 안함
    properties:
      hibernate:
        format_sql: true
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    url: /openapi3.yaml

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000
