# 공통

server:
  port: 8080

spring:
  application:
    name: pigrest-server

  profiles:
    active: dev

  output:
    ansi:
      enabled: always

logging:
  level:
    root: info
    app.pigrest: debug